### ISSUE TITLE
Voeg een geometrie kolom toe mét spatial index

### ISSUE THREAD

**Issue by VerdoodtDries** [davidvlaminck/AWVInfraPostGISSyncer#6]
Aan de tabel *geometrie* een kolom toevoegen met data type "geometry". Een spatial index toevoegen aan deze kolom.
Queries zullen sneller worden uitgevoerd mét een spatial index op een spatial kolom.

`-- DDL alter table
ALTER TABLE public.geometrie ADD geom public.geometry NULL;
COMMENT ON COLUMN public.geometrie.geom IS 'geometry column';

-- DML update column, fill geometrie column
UPDATE public.geometrie
SET geom=st_geomfromtext(wkt_string, 31370);

-- Build a spatial index
CREATE INDEX idx_geometrie ON public.geometrie USING GIST (geom);

-- Refresh the spatial index
REINDEX INDEX idx_geometrie;

-- Vacuum dead tuples and analyse queries to optimize the query plan
VACUUM ANALYZE public.geometrie;
`

**Comment by davidvlaminck** [comment]
fixed in https://github.com/davidvlaminck/AWVInfraPostGISSyncer/commit/635df5a762c2807e9751923a699cd62267451b45
